### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by tmigot** [Farhad-phd/FluxNLPModels.jl#2]
I would copy-paste and fill in this one https://github.com/JuliaSmoothOptimizers/JSOTemplate.jl/blob/main/README.md

you can also take this as an example

https://github.com/JuliaSmoothOptimizers/DCISolver.jl/blob/main/README.md

**Comment by tmigot** [comment]
Usually https://github.com/Farhad-phd/FluxNLPModels.jl/blob/main/docs/src/index.md is the same as the readme without the badges.

**Comment by farhadrclass** [comment]
Added the read me 
Todo is make sure the links are working 
@tmigot would you be able to check this? also I wrote them as if the package is already added to JSO
